# Generated by Django 3.2.23 on 2023-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='private_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
