# Generated by Django 3.2.23 on 2023-11-07 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20231107_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schedule',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
