# Generated by Django 3.2.23 on 2023-11-20 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20231107_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_of_the_week',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
