# Generated by Django 3.2.23 on 2023-11-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20231121_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day_of_the_week',
        ),
        migrations.RemoveField(
            model_name='privatesession',
            name='day_of_the_week',
        ),
    ]
