# Generated by Django 3.2.23 on 2023-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20231122_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='actual_participants',
            field=models.IntegerField(default=0),
        ),
    ]
