# Generated by Django 3.2.23 on 2023-11-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0007_auto_20231124_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_periods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
