# Generated by Django 3.2.23 on 2023-11-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_unavailableperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailableperiod',
            name='slug',
            field=models.SlugField(default='unavailable-period', max_length=255),
        ),
    ]
