# Generated by Django 3.2.23 on 2023-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_unavailableperiod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailableperiod',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
