# Generated by Django 3.2.23 on 2023-12-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_alter_unavailableperiod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatesession',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
