# Generated by Django 3.2.23 on 2023-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_privatesession_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
