# Generated by Django 3.2.23 on 2023-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0012_auto_20231201_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatesession',
            name='location',
            field=models.CharField(choices=[('location1', 'Salle de sport(partenaire)'), ('location2', 'A domicile'), ('location3', 'En extérieur'), ('location4', 'Autre')], max_length=255),
        ),
    ]
